mprib/caliscope

src/calibration/bundle_adjustment/point_data.py
src/cameras/camera_array.py

working now, though not updating to the camera array

Intrinsic parameter variation in xy reprojection error

---

src/cameras/camera_array.py

The goal was achieved but the feature didn't really work the way I'd hoped. Just stick with the simple way of getting camera intrinsics and don't mess with it. Get a good low RMSE and move on....

Update camera intrinsics following Bundle Adjustment

---

requirements.txt
src/gui/main.py
src/gui/stereo_calibration/stereo_frame_builder.py

had only been using one function that could be rewritten in 4 lines of code...

Remove dependency on imutils

---

calicam/gui_wizard/wizard_calibration/omni_frame_builder.py

To keep the omni frame from disappearing and throwing an error in Qt, this placeholder gets thrown up to indicate that the target board count has been achieved for each pair of cameras

Create data collection complete frame

---

README.md
calicam/calibration/capture_volume/corner_distance_accuracy.py
calicam/calibration/capture_volume/quality_scanner.py

QualityScanner now serves as a more stable and explicit way to obtain the corner distance accuracy.
Given the intermediate data that it summarizes in that process, it is also a somewhat natural place to subset the PointEstimates used by the CaptureVolume for the optimization. The previous filtering was not updating the 3D points or considering that some of those triangulated points may cease to exist and then throw everything off. This is where the data processing needs to be quite careful and is why I believe it was not looking so great post-filtration previously.

159 create qualityscanner

---

README.md

vs code kept wanting to publish the branch again..not sure what's going on

improve wording

---

pyxy3d/gui/vizualize/capture_volume_dialog.py
pyxy3d/gui/vizualize/capture_volume_visualizer.py

slider + capture volume visualizer working well. Don't bother with integrating with the actual images frames just yet...
Next up: need to calculate the pose of the charuco board for setting of the origin...

slider across collected points working

---

pyproject.toml
pyxy3d/__init__.py

Bump version v0.0.14 -> v0.0.15; refresh PyPI

---

pyxy3d/__init__.py
pyxy3d/calibration/capture_volume/capture_volume.py
pyxy3d/calibration/capture_volume/point_estimates.py
pyxy3d/cameras/camera_array.py
pyxy3d/gui/vizualize/capture_volume_widget.py
pyxy3d/recording/recorded_stream.py
pyxy3d/session.py
tests/test_calibration.py

Started making some changes and realized there were some integration issues because I'm not saving out to the config from the object, but rather via the session. I can see now that this coupling introduces some binds that I don't want to have in the future. not going to do anything about it now, but something important to keep in mind. Creating an issue on Someday/Maybe...

247 load capture volume into viz from config

---

dev/demo/demo_gui_calibration.py
dev/demo/demo_gui_recording.py
dev/demo/demo_process_prerecorded.py
pyproject.toml
pyxy3d/__main__.py
pyxy3d/calibration/monocalibrator.py
pyxy3d/cameras/camera.py
pyxy3d/gui/calibration_wizard.py
pyxy3d/gui/main.py
pyxy3d/gui/recording_widget.py
pyxy3d/gui/vizualize/playback_triangulation_widget.py
pyxy3d/session.py

appears to be in good working order... realizing it is good policy to move demo scripts into command line launchables....
Still the case that my tests are not expanding as I would like... just want to acknowledge that.

296 calibration wizard to calibration widget

---

pyxy3d/post_processing_pipelines.py
pyxy3d/recording/recorded_stream.py
pyxy3d/recording/video_recorder.py
tests/test_calibration.py
tests/test_hand_tracker.py
tests/test_hand_triangulation.py
tests/test_real_time_triangulator.py

fixed and passing. Be careful when creating post-processed versions of data! Writing to a file while reading from it took awhile to track down....

305 fix failing tests after csv purge

---

pyxy3d/cameras/live_stream.py
pyxy3d/gui/post_processing_widget.py
pyxy3d/gui/vizualize/playback_triangulation_widget.py
pyxy3d/post_processing_pipelines.py

Threading solution to kick off processing, including locking down the interface during it. Trying to prioritize what my next steps might be here.....Time to go back to the project board.

313 create xyz within thread

---

dev/demo/demo_capture_volume_visualizer.py
dev/demo/demo_gui_postprocess.py
dev/demo/demo_gui_recording.py
pyxy3d/gui/vizualize/calibration/capture_volume_widget.py

simple fix....need to save capture volume via configurator and not via session.

318 fix postprocessing origin bug

---

pyxy3d/configurator.py
tests/test_configurator.py

good quick update and something that can help to keep the config more readable. 
Testing updated to confirm working, and backwards compatible with old config files...

317 config saves rotation as rodrigues

---

pyxy3d/export.py
pyxy3d/gui/post_processing_widget.py
pyxy3d/post_processing_pipelines.py

simple export of wide and trc when pressing the Export button. Nothing fancy. Could also get bundled up into "process." In fact that is what I should do....I'll do it now...

316 export from postprocessing widget

---

dev/demo/demo_gui_calibration.py
pyxy3d/calibration/monocalibrator.py
pyxy3d/gui/calibration_widget.py
pyxy3d/gui/camera_config/camera_config_dialogue.py
pyxy3d/gui/stereoframe/stereo_frame_builder.py

Looks like this was a pretty quick fix. I think things are in a good place for tomorrow to integrate everything into a Main window. That may take a few days, but it really is the last of it before moving onto purely cosmetic / OpenSim issues.

frame resizing to square; tests passing

---

pyxy3d/calibration/monocalibrator.py
pyxy3d/cameras/live_stream.py
pyxy3d/configurator.py
pyxy3d/gui/camera_config/camera_config_dialogue.py
pyxy3d/gui/camera_config/camera_summary_widget.py
pyxy3d/gui/camera_config/camera_tabs.py
pyxy3d/gui/navigation_bars.py
pyxy3d/gui/stereoframe/stereo_frame_widget.py

In the process of looking into this I realized it wasn't really worth investing in getting this to work right now, but did find various other GUI issues that I wanted to sort out.

336 ability to abandon intrinsic calibration early

---

pyxy3d/gui/extrinsic_calibration_widget.py
pyxy3d/post_processor.py
pyxy3d/recording/video_recorder.py
pyxy3d/session/session.py
tests/test_calibration.py
tests/test_hand_triangulation.py
tests/test_real_time_triangulator.py

Config now getting stored upon initiation of recording. Also stopped storing xy.csv when points were not being tracked (new parameter to set point history storage to allow fine grain control...it doesn't automatically trigger based on tracking).

355 config stored in recording folder

---

dev/demo/demo_gui_calibrate_capture_volume.py
dev/demo/demo_gui_capture_volume.py
pyxy3d/calibration/stereocalibrator.py
pyxy3d/configurator.py
pyxy3d/gui/calibrate_capture_volume_widget.py
pyxy3d/gui/calibration_widget.py
pyxy3d/gui/charuco_widget.py
pyxy3d/gui/extrinsic_calibration_widget.py
pyxy3d/gui/main_widget.py
pyxy3d/gui/navigation_bars.py
pyxy3d/gui/vizualize/calibration/capture_volume_visualizer.py
pyxy3d/gui/vizualize/calibration/capture_volume_widget.py
pyxy3d/gui/wizard_charuco.py
pyxy3d/session/session.py

separate tabs are being created now and launch as approprate based on the camera connection initiating.

364 split out tabs for charucocamerascalibration

---

dev/demo/demo_gui_main.py
dev/demo/demo_gui_recording.py
pyxy3d/gui/calibration_widget.py
pyxy3d/gui/camera_config/intrinsic_calibration_widget.py
pyxy3d/gui/main_widget.py
pyxy3d/recording/video_recorder.py
pyxy3d/session/session.py

Cutting short resolved though future revisions needed to disable the button while recording has stopped but before all frames are saved.

365 recording cuts short

---

dev/demo/demo_gui_intrinsic_calibration.py
pyxy3d/cameras/camera_array.py
pyxy3d/gui/camera_config/intrinsic_calibration_widget.py
pyxy3d/gui/vizualize/playback_triangulation_widget.py

Made some small changes planning to make bigger changes but then realized the goal of the branch was kinda pointless and could be made unnecessary by better blocking of dead ends earlier in the UI

378 processing tab can always be loaded

---

pyxy3d/calibration/monocalibrator.py
pyxy3d/gui/calibrate_capture_volume_widget.py
pyxy3d/gui/extrinsic_calibration_widget.py
pyxy3d/gui/main_widget.py
pyxy3d/gui/recording_widget.py
pyxy3d/session/session.py

I am not seeing this toggle into "await" but then it might have to do with the recording finishing "too quickly". I'm going to move forward with this solution and address it more if things start to break.

372 record button reflects saving process

---

dev/dev_low_pass_filter.py

the basic functionality is there in this dev script. It doesn't make terribly good improvements in the outcome, so I don't see this as a priority to invest in right now, particularly as other tools may be better equipped to perform the filtering of this data. 
Turn attention back to building integration with other tools. Perhaps returning to target OpenSim which may be rather close to a useful place.

basic filter functionality is in this dev script

---

pyxy3d/gui/recording_widget.py

The fix here was actually about getting the recording frame pixmap to a size that allowed the width to be divisible by 4. This is something to do with Qt and I'm grateful to chatGPT for helping me sort it out.

add padding so dims divisible by 4 for pixmap

---

pyxy3d/cameras/camera.py

primarily updating some comments. close #416  as not worth fighting for. This is a finicky hardware issue that I want to solve with hardware

non emeet cameras perform poorly...hold off 

---

pyxy3d/recording/recorded_stream.py
pyxy3d/recording/video_recorder.py
tests/test_synchronizer.py

test up and running now... able to move forward with some refactors I was previously afraid to touch...

419 create test for synchronizer

---

dev/demo/demo_gui_extrinsic_calibration.py
dev/demo/demo_gui_intrinsic_calibration.py
dev/demo/demo_gui_recording.py
pyxy3d/cameras/synchronizer.py
pyxy3d/gui/camera_config/frame_emitter.py
pyxy3d/gui/camera_config/intrinsic_calibration_widget.py
pyxy3d/gui/extrinsic_calibration_widget.py
pyxy3d/gui/recording_widget.py
pyxy3d/gui/single_main_widget.py
pyxy3d/session/session.py

Largely working though some crashed identified with multicamera calibration / capture volume loading. This is a more targetted issue and I'll create separate branches to deal with those. In the meantime, this is meaningful progress.

426 main window calls up widgets one by one

---

dev/dev_xy_gap_fill.py
pyxy3d/gui/single_main_widget.py
pyxy3d/post_processing/gap_filling.py
tests/reference/base_data/README.md
tests/test_gap_fill_xy.py

Basic test and implementation of function. Integrating with PostProcessor and GUI can wait. Should be set up for a quick (x,y,z) filter tomorrow.

439 interpolate small gaps in xy estimates

---

pyxy3d/cameras/camera.py
pyxy3d/post_processing/gap_filling.py
tests/test_gap_fill.py

I don't think this made much of a difference at all, but it also didn't take long to run... just another piece of an ultimate complete pipeline for processing.

440 interpolate small gaps in xyz estimates

---

LICENSE.md
README.md

Revert "444 revise to bsd 2 clause"

---

pyxy3d/gui/recording_widget.py
pyxy3d/gui/single_main_widget.py

GUI is super stable now. Quite happy with it.

454 fix crash on mode switch

---

pyxy3d/gui/recording_widget.py

Issue resolved by wrapping up the call to stop recording to its own thread.

push call to session to its own thread

---

pyxy3d/gui/post_processing_widget.py
pyxy3d/post_processing/post_processor.py

458 catch lack of tracked points in post processor

---

poetry.lock
pyproject.toml
pyxy3d/cameras/live_stream.py
pyxy3d/recording/video_recorder.py

Fixes the recording issue by making sure that stream.size is dynamic and adjusts as the underlying camera resolution adjusts. It achieves this by converting size to a @property decorated method.

469 restore recording functionality on laptop

---

dev/dev_recalibrate_from_xy.py
docs/index.md
pyxy3d/session/session.py
pyxy3d/trackers/holistic_opensim_tracker.py

able to generate sample ballet demo from this.

475 recalibrate extrinsics from xy and config

---

.gitignore
poetry.lock
pyproject.toml
pyxy3d/__init__.py
pyxy3d/cameras/camera.py

Potential fix to issues on macOS 14. Works well on macOS 13...

Switch os.name to platform.version

---

pyxy3d/cameras/live_stream.py
pyxy3d/interface.py
pyxy3d/recording/recorded_stream.py
tests/test_stream.py

Basic functionality to pause/play/jump is now incorporated into the RecordedStream.
This should provide the handles needed for a controller layer to interact with.

491 recorded stream can pause play jump

---

dev/dev_playback_widget.py
pyxy3d/controller.py
pyxy3d/playback_frame_emitter.py
pyxy3d/recording/recorded_stream.py

Basic integration in place now... Not yet able to select individual frames via slider, which should be the target of the next branch

integrate recorded stream playback with display widget via frame emitter

---

pyxy3d/calibration/intrinsic_calibrator.py
pyxy3d/controller.py
pyxy3d/recording/recorded_stream.py
tests/test_controller.py
tests/test_intrinsic_calibrator.py

Core calibration working well here. Note that grid history will need to be pulled out of this (currenlty not functional) and folded in to the frame_emitter.

502 intrinsic calibrator accepts point packets as inputs

---

dev/dev_playback_widget.py
pyxy3d/calibration/draw_charuco.py
pyxy3d/calibration/intrinsic_calibrator.py
pyxy3d/controller.py
pyxy3d/playback_frame_emitter.py
tests/test_intrinsic_calibrator.py

board data populates to the intrinsic calibrator as the stream is played out out to the GUI, and the GUI allows flagging of frame indices for the final calibration.

504 construct function to generate grid history from points

---

dev/dev_playback_widget.py
pyxy3d/calibration/intrinsic_calibrator.py
pyxy3d/controller.py

Basic functionality in place... next step is to display the results of a calibration to the user...

updates to enable intrinsic calibration from GUI

---

pyxy3d/calibration/intrinsic_calibrator.py
pyxy3d/cameras/camera_array.py
pyxy3d/controller.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py
pyxy3d/playback_frame_emitter.py

Basic functionality in place with mild improvements in the layout of the playback widget. From here need to fold in the ability to apply the distortion model to the frame. Which I guess should be a checkbox or something?

513 clear calibration data

---

pyxy3d/controller.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py
pyxy3d/playback_frame_emitter.py

Undistortion is being applied to the emitted frame, but I do think there is an issue with the resulting frame getting overly cropped...

distortion model now being applied within frame emitter

---

pyxy3d/controller.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py
pyxy3d/playback_frame_emitter.py

Appears to be working though current test data has such small FOV coverage that things definitely look wonky. Which is kinda the point, I suppose... weird calibration results should jump out as weird.

optimal camera matrix used to show all undistorted pixels

---

.gitignore
pyxy3d/controller.py
pyxy3d/gui/charuco_widget.py

Basic functionality in place with controller rather than "Session"

525 integrate charuco builder with controller

---

pyxy3d/gui/charuco_widget.py
pyxy3d/gui/prerecorded_intrinsic_calibration/multiplayback_widget.py
pyxy3d/gui/prerecorded_main_widget.py
pyxy3d/playback_frame_emitter.py

The core objectives of the branch are achieved, though it is clear that with the various widgets set within one another that the sizing policies are going to need to be set better.... though I'll worry about that as the full basic functionality is in place.

530 main widget with charuco and intrinsic cal

---

dev/demo/demo_playback_widget.py
dev/demo/demo_synched_frames_widget.py
pyxy3d/calibration/capture_volume/capture_volume.py
pyxy3d/cameras/synchronizer.py
pyxy3d/controller.py
pyxy3d/extrinsic_stream_manager.py
pyxy3d/gui/extrinsic_playback_widget.py
pyxy3d/gui/frame_emitters/frame_dictionary_emitter.py
pyxy3d/gui/frame_emitters/playback_frame_emitter.py
pyxy3d/gui/frame_emitters/tools.py
pyxy3d/gui/prerecorded_intrinsic_calibration/multiplayback_widget.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py
pyxy3d/gui/prerecorded_main_widget.py
pyxy3d/gui/recording_widget.py
pyxy3d/gui/synched_frames_widget.py
pyxy3d/gui/vizualize/calibration/capture_volume_widget.py
pyxy3d/helper.py
pyxy3d/recording/recorded_stream.py
pyxy3d/recording/video_recorder.py
pyxy3d/synchronized_stream_manager.py
pyxy3d/trackers/charuco_tracker.py
tests/test_controller.py
tests/test_real_time_triangulator.py
tests/test_sync_stream_manager.py

Basic playback of multiple concurrent streams with tracking visualized and 2d data stored.
This will be the foundation of both the extrinsic calibration as well as the general motion tracking and triangulation...

532 create extrinsic playback widget

---

pyxy3d/gui/prerecorded_main_widget.py
pyxy3d/recording/recorded_stream.py

Lightweight changes to pull in capture volume.... More challenging part will be using workspace manager to make sure that GUI doesn't try to load this when it doesn't exist...

Minimal changes to load preconfigured capture_volume

---

dev/demo/demo_playback_widget.py
pyxy3d/gui/frame_emitters/playback_frame_emitter.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py

Basic functionality implemented here to scale the image. Along the way ended up cleaning the Camera GUI up a little bit.

scaling factor applied to undistorted image to improve visibility

---

dev/demo/demo_gui_capture_volume.py
dev/demo/demo_playback_widget.py
dev/demo/demo_synched_frames_widget.py
pyxy3d/controller.py
pyxy3d/gui/charuco_widget.py
pyxy3d/gui/prerecorded_intrinsic_calibration/multiplayback_widget.py
pyxy3d/gui/prerecorded_intrinsic_calibration/playback_widget.py
pyxy3d/gui/prerecorded_main_widget.py
pyxy3d/gui/synched_frames_widget.py
pyxy3d/intrinsic_stream_manager.py
pyxy3d/synchronized_stream_manager.py
tests/test_controller.py

Some mild improvements in clarity within the controller. Time to reorient toward converting controller to a WorkspaceManager that will allow verification of where the calibration process is and can then provide useful properties for the GUI to enable/load and disable/not load Widgets...

545 create intrinsic stream manager

---

pyxy3d/controller.py
pyxy3d/gui/main_widget.py
pyxy3d/gui/post_processing_widget.py
pyxy3d/gui/workspace_widget.py
pyxy3d/workspace_guide.py

Not the prettiest thing in the world, but it makes basic checks and lets the user know where files need to be populated and what they need to be named.

559 workspace guide to catalog checkpoints

---

pyxy3d/controller.py
tests/test_controller.py

Unable to duplicate issue of capture volume widget functionality being compromised so it may have been resolved in a recent branch. Pushing changes back that improve logging.

Reduce cluttered logging

---

pyxy3d/configurator.py
pyxy3d/controller.py
pyxy3d/gui/camera_management/camera_display_widget.py
pyxy3d/gui/camera_management/playback_widget.py
pyxy3d/gui/frame_emitters/playback_frame_emitter.py
pyxy3d/gui/workspace_widget.py
tests/test_controller.py

In the midst of working on this branch I've made some fixes to a weird issue that came up where it seems pointers to the camera by the calibrator and the controller got disjointed. That is resolved in the commits below, so I'm pushing this back to main prior to completing the branch goals.

573 reloading the workspace freezes gui - patching camera pointer issue

---

poetry.lock
pyproject.toml
pyxy3d/__init__.py
pyxy3d/calibration/capture_volume/quality_controller.py
pyxy3d/calibration/charuco.py
pyxy3d/calibration/stereocalibrator.py
pyxy3d/cameras/camera_array_initializer.py
pyxy3d/configurator.py
pyxy3d/gui/main_widget.py
pyxy3d/gui/old_main_widget.py
pyxy3d/gui/vizualize/camera_mesh.py
pyxy3d/recording/recorded_stream.py
tests/test_real_time_triangulator.py
tests/test_smoothing.py

switch from toml to rtoml. substantial speed improvement

---

pyxy3d/controller.py
pyxy3d/gui/main_widget.py
pyxy3d/gui/post_processing_widget.py
pyxy3d/gui/vizualize/calibration/capture_volume_widget.py
pyxy3d/post_processing/post_processor.py

The post processor will now archive the config.toml into the subdirectory with the processed/triangulated data. 
In the GUI display, if processing has been done then it will display the camera array at the time of the processing, otherwise it shows the current array (same as in the capture volume widget).

560 post processing stashes reference config with tracked subfolder

---

pyxy3d/gui/post_processing_widget.py
tests/test_metarig_config_json.py

Tests still passing and button functionality is back in place. Still need to check in on the Rigmarole code which is a bit of a blank spot in my mind at the moment.

Restore metrig config generation capacity in post processing

---

pyxy3d/gui/camera_management/playback_widget.py
pyxy3d/gui/main_widget.py

Minor changes, primarily better grouping and size of buttons.
May want to make "Show Distortion" and "Zoom" buttons have more sensible enable/disable functionality, but that is low priority at the moment.

588 clean up playback widget buttons

---

caliscope/__init__.py
caliscope/export.py
caliscope/post_processing/post_processor.py
caliscope/post_processing/smoothing.py

Determined that issue was related to the low fps of the demo footage alongside the 6Hz lowpass butterworth filter. 
As filtering is not a primary function of this package, I have toggled off those stages of post-processing to potentially be revisited later.

619 xyz not getting created in post processing

---

caliscope/trackers/face_tracker.py
caliscope/trackers/tracker_enum.py

- Copy pasted `hand_tracker.py`, and changed keywords "HAND" into "FACE".
- Borrowed mediapipe landmark names from `tfjs-models`, and used it for face landmark coloring.

Face tracker

---

pyproject.toml

Tweaks made to default GUI values and want to make sure that PyPI reflects new values.

Bumps minor version after previous changes to autocalibrate defaults

---

.github/workflows/draft-pdf.yml
.github/workflows/mkdocs.yaml
.github/workflows/pytest.yml

This reverts commit 7bf771bc0ecdd5e4987a792d78b1f06e7207d66e.

Revert "run tests on push, but don't bother with pdf recreation"

---

caliscope/calibration/stereocalibrator.py

Reporting RMSE does not make sense in the refactored context as we are now dealing with normalized image points.

clean up logging

---

caliscope/calibration/capture_volume/capture_volume.py
caliscope/calibration/capture_volume/helper_functions/get_stereotriangulated_table.py
caliscope/cameras/camera_array.py
caliscope/gui/synched_frames_display.py
caliscope/gui/workspace_widget.py
caliscope/packets.py
caliscope/triangulate/array_stereo_triangulator.py
caliscope/triangulate/stereo_points_builder.py
caliscope/triangulate/sync_packet_triangulator.py
caliscope/triangulate/triangulation.py
dev/demo/demo_synched_frames_widget.py
tests/test_not_sufficient_stereopairs.py
tests/test_optimization_unlinked.py
tests/test_triangulator.py
tests/test_xy_to_xyz.py

previously there was a mix of approaches for undistorting the image points to a normalized / perfect camera frame of reference. This commit consolidates all undistortion logic to the CameraData method

All undistort calls running through CameraData method
